interface Equipment {
    name: string;
    quantity: number;
    model: string;
    capacity: string;
    highlight?: boolean;
}
export const equipmentList: Equipment[] = [
    {
        name: "門型マシニングセンター",
        quantity: 3,
        model: "MPC-3680\nMPE-2140\nMPF-3116FS",
        capacity: "8000×3100×1965\n4000×1800×1050\n1900×3100×1150",
    },
    {
        name: "横中ぐりフライス盤",
        quantity: 2,
        model: "BTD-130H.R22\nBTD-13FR22",
        capacity: "3000×2300×1600\n3000×2300×1600",
    },
    {
        name: "縦型マシニングセンター",
        quantity: 1,
        model: "MV-80C",
        capacity: "2600×814",
    },
    {
        name: "縦型NC旋盤(ターニング)",
        quantity: 1,
        model: "TUD-20",
        capacity: "φ2500×1850",
    },
    {
        name: "縦型マシニングセンター",
        quantity: 1,
        model: "MV-80C",
        capacity: "2600×814",
    },
    {
        name: "縦型マシニングセンター",
        quantity: 1,
        model: "MV-80C",
        capacity: "2600×814",
    },
    {
        name: "縦型マシニングセンター",
        quantity: 1,
        model: "MV-653/50",
        capacity: "1530×660",
    },
    {
        name: "縦型マシニングセンター",
        quantity: 1,
        model: "MV-65/50",
        capacity: "1260×640",
    },
    {
        name: "ワイヤ放電加工機",
        quantity: 1,
        model: "MP2400",
        capacity: "1050×82×305",
    },
    {
        name: "3次元測定機",
        quantity: 0,
        model: "CRYSTA-ApexS163012",
        capacity: "1600×3000×1200",
    },
    {
        name: "縦型汎用フライス盤",
        quantity: 3,
        model: "YZ-8C",
        capacity: "1500×350",
    },
    {
        name: "横型汎用フライス盤",
        quantity: 1,
        model: "HF-2",
        capacity: "270×1100",
    },
    {
        name: "CNC複合旋盤",
        quantity: 1,
        model: "SC-250",
        capacity: "φ250",
    },
    {
        name: "CNC複合旋盤",
        quantity: 1,
        model: "SL-250BMC",
        capacity: "φ250×300",
    },
    {
        name: "CNC複合旋盤",
        quantity: 1,
        model: "NL-3000Y",
        capacity: "φ300×700",
    },
    {
        name: "CNC複合旋盤",
        quantity: 1,
        model: "シンコムEL42",
        capacity: "φ42",
    },
    {
        name: "CNC複合旋盤",
        quantity: 2,
        model: "シンコムEL16",
        capacity: "φ16",
    },
    {
        name: "CNC複合旋盤",
        quantity: 1,
        model: "ZL-15SM",
        capacity: "φ40",
    },
    {
        name: "NC旋盤",
        quantity: 1,
        model: "LL-7B",
        capacity: "φ800×3500",
    },
    {
        name: "NC旋盤",
        quantity: 1,
        model: "LG-71",
        capacity: "φ100×50",
    },
    {
        name: "NC旋盤",
        quantity: 1,
        model: "M-4",
        capacity: "φ250×800",
    },
    {
        name: "12尺汎用旋盤",
        quantity: 1,
        model: "STRONG2000",
        capacity: "φ600×2000",
    },
    {
        name: "12尺汎用旋盤",
        quantity: 1,
        model: "TE3000",
        capacity: "φ600×3000",
    },
    {
        name: "8尺汎用旋盤",
        quantity: 3,
        model: "TAL600",
        capacity: "φ380×1500",
    },
    {
        name: "8尺汎用旋盤",
        quantity: 1,
        model: "TAL560",
        capacity: "φ450×1500",
    },
    {
        name: "8尺汎用旋盤",
        quantity: 1,
        model: "DLG-SH",
        capacity: "φ380×1200",
    },
    {
        name: "6尺汎用旋盤",
        quantity: 2,
        model: "860",
        capacity: "φ250×1000",
    },
    {
        name: "4尺汎用旋盤",
        quantity: 2,
        model: "TSL-550D",
        capacity: "φ150×500",
    },
    {
        name: "正面汎用旋盤",
        quantity: 1,
        model: "TFL-1600",
        capacity: "φ1600×1200",
    },
    {
        name: "卓上旋盤",
        quantity: 1,
        model: "KL-25",
        capacity: "-",
    },
    {
        name: "摩擦圧接機",
        quantity: 1,
        model: "FWD-30",
        capacity: "φ30×240",
    },
    {
        name: "スロッター",
        quantity: 1,
        model: "SL-200",
        capacity: "φ550×200",
    },
    {
        name: "全自動鋸盤",
        quantity: 1,
        model: "HA-300S",
        capacity: "-",
    },
    {
        name: "帯鋸盤",
        quantity: 1,
        model: "KC-600",
        capacity: "-",
    },
    {
        name: "製缶プレス",
        quantity: 1,
        model: "HPFR-200VWS",
        capacity: "200ton",
    },
    {
        name: "形鋼切断用バンドリー",
        quantity: 3,
        model: "HK700",
        capacity: "-",
    },
    {
        name: "油圧式シャーリング",
        quantity: 1,
        model: "C10",
        capacity: "t10×3100",
    },
    {
        name: "平面研削盤",
        quantity: 1,
        model: "PSG-155DX",
        capacity: "500×1500",
    },
    {
        name: "平面研削盤",
        quantity: 1,
        model: "PSG-10",
        capacity: "350×1000",
    },
    {
        name: "円筒研削盤",
        quantity: 1,
        model: "UGK-450H-TS",
        capacity: "φ150×450",
    },
    {
        name: "センタレスグラインダ",
        quantity: 1,
        model: "Hi-GRiND",
        capacity: "φ3.0～φ30",
    },
    {
        name: "センタレスグラインダ",
        quantity: 1,
        model: "GR200×45N",
        capacity: "φ3.0～φ60",
    },
    {
        name: "バレル研磨機",
        quantity: 1,
        model: "TM-8型",
        capacity: "-",
    },
    {
        name: "ラジアルボール盤",
        quantity: 1,
        model: "HOR-2000",
        capacity: "-",
    },
    {
        name: "大型ボール盤",
        quantity: 1,
        model: "YUD-700",
        capacity: "-",
    },
    {
        name: "NCボール盤",
        quantity: 1,
        model: "MFC-510T",
        capacity: "-",
    },
    {
        name: "卓上ボール盤",
        quantity: 3,
        model: "-",
        capacity: "-",
    },
    {
        name: "タッピングボール盤",
        quantity: 2,
        model: "-",
        capacity: "-",
    },
    {
        name: "アイアンワーカー",
        quantity: 1,
        model: "iW45",
        capacity: "-",
    },
    {
        name: "コンターマシン",
        quantity: 1,
        model: "NCC400LE",
        capacity: "-",
    },
    {
        name: "スポット溶接機",
        quantity: 1,
        model: "iD40ST",
        capacity: "-",
    },
    {
        name: "ティグ溶接機",
        quantity: 18,
        model: "T500-P",
        capacity: "-",
    },
    {
        name: "アーク溶接機",
        quantity: 1,
        model: "-",
        capacity: "-",
    },
    {
        name: "半自動溶接機",
        quantity: 6,
        model: "AAⅡ-500",
        capacity: "-",
    },
    {
        name: "プラズマ切断機",
        quantity: 1,
        model: "PF-60",
        capacity: "-",
    },
    {
        name: "投影機",
        quantity: 1,
        model: "V12",
        capacity: "-",
    },
    {
        name: "ポジショナー",
        quantity: 5,
        model: "PKE-10",
        capacity: "-",
    },
    {
        name: "偏心検査機",
        quantity: 3,
        model: "-",
        capacity: "-",
    },
    {
        name: "テーブル集塵機",
        quantity: 1,
        model: "HMD-1600P",
        capacity: "-",
    },
    {
        name: "酸洗公害防止設備",
        quantity: 1,
        model: "-",
        capacity: "-",
    },
    {
        name: "プラズマ溶接機",
        quantity: 1,
        model: "350AH-V",
        capacity: "-",
    },
    {
        name: "プラズマ溶接機用ロボット",
        quantity: 1,
        model: "MOTOMAN-AR1730",
        capacity: "-",
    },
    {
        name: "スーパーシャイナー",
        quantity: 2,
        model: "SUPER SHINER-M2",
        capacity: "-",
    },
    {
        name: "自動プログラムシステム",
        quantity: 2,
        model: "CAD/CAM",
        capacity: "-",
    },
    {
        name: "自動プログラムシステム",
        quantity: 1,
        model: "AP100",
        capacity: "-",
    },
    {
        name: "AutoCAD",
        quantity: 6,
        model: "-",
        capacity: "2次元CAD",
    },
    {
        name: "SolidWorks",
        quantity: 2,
        model: "-",
        capacity: "3次元CAD",
    },
    {
        name: "ホイストクレーン(塩崎工場)",
        quantity: 3,
        model: "-",
        capacity: "5ton",
    },
    {
        name: "ホイストクレーン(塩崎工場)",
        quantity: 1,
        model: "-",
        capacity: "4.8ton",
    },
    {
        name: "ホイストクレーン(塩崎工場)",
        quantity: 2,
        model: "-",
        capacity: "2.8ton",
    },
    {
        name: "ホイストクレーン(本社工場)",
        quantity: 2,
        model: "-",
        capacity: "30ton(20+10)",
    },
    {
        name: "ホイストクレーン(本社工場)",
        quantity: 3,
        model: "-",
        capacity: "10t",
    },
    {
        name: "ホイストクレーン(本社工場)",
        quantity: 3,
        model: "-",
        capacity: "5t",
    },
    {
        name: "ホイストクレーン(本社工場)",
        quantity: 1,
        model: "-",
        capacity: "2.8t",
    },
];